# Generated by Django 3.0.8 on 2020-07-25 13:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=70)),
                ('category_text', models.CharField(max_length=30)),
                ('preview_text', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('body', models.TextField(blank=True)),
                ('dete_pub', models.DateField()),
                ('youtube_link', models.SlugField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CatPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='InstPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_link', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('photo_path', models.FilePathField()),
                ('product_slug', models.SlugField(max_length=30, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_photo', models.FilePathField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='n_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='overall_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes_female',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), default=None, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes_juniors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), default=None, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes_male',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), default=None, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='special_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='val4money',
            field=models.FloatField(null=True),
        ),
    ]
