# Generated by Django 3.0.8 on 2020-07-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martens', '0002_auto_20200725_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='category_text',
            new_name='cat_text',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='preview_text',
            new_name='pvw_text',
        ),
        migrations.RenameField(
            model_name='instpost',
            old_name='product_name',
            new_name='prod_name',
        ),
        migrations.RenameField(
            model_name='instpost',
            old_name='product_photo',
            new_name='prod_photo',
        ),
        migrations.RenameField(
            model_name='instpost',
            old_name='product_slug',
            new_name='prod_slug',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='dete_pub',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_pub',
            field=models.DateField(default=None),
        ),
    ]
